name: Open PR

on:
  workflow_dispatch:

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create branch and change
        run: |
          git checkout -b ghs-pr-heartbeat
          touch file.txt
          git add file.txt
          git commit -m "Add file"
          git push origin ghs-pr-heartbeat

      - name: Create pull request
        run: gh pr create -B main -H ghs-pr-heartbeat --title "Heartbeat PR" --body "Created by GitHub Action"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
